name: test ymal
on: push
jobs:
  job1:
    name: first job
    runs-on: windows-latest
    steps:
      - name: steps one
        uses: actions/checkout@v2
      - name: steps two
        run: echo "test is working"

  job3:
    name: job 3
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: first job
        run: echo "third job is finished"

  job2:
    name: second job
    runs-on: ubuntu-latest
    steps:
      - name: strps one
        uses: actions/checkout@v2
      - name: steps two
        run: env | sort
      - name: 'print'
        uses: actions/github-script@v3
        id: set-result
        with:
           script: |
              var fs = require('fs'); 
              const filepath = './src/versionInfo.js';
              const packageJSON = require('./package.json');
              fs.writeFileSync(filepath,`export default { version:'${packageJSON.version}'};`);

